name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            header.tex
            resume.tex

